# llm/mock_provider.py
# This file is part of the OpenLLM project

"""Mock LLM provider — returns rule-based analysis without any API calls."""
import logging
from app.llm.base import BaseLLMProvider

logger = logging.getLogger(__name__)


# This is a simple mock provider for V1 to allow testing the overall flow without integrating a real LLM API.
class MockLLMProvider(BaseLLMProvider):
    """
    Mock provider for V1. Returns deterministic analysis based on keyword presence.
    Replace with a real provider (OpenAI, Claude, Gemini) in V2.
    """

    provider_name = "mock"

    def is_available(self) -> bool:
        return True

    def analyze_job(self, job_title: str, job_description: str, profile_summary: str) -> str:
        desc_lower = job_description.lower()
        title_lower = job_title.lower()

        highlights = []
        concerns = []

        if "python" in desc_lower:
            highlights.append("Python is a core skill match")
        if any(kw in desc_lower for kw in ["llm", "rag", "ai", "ml"]):
            highlights.append("AI/ML focus aligns with your target roles")
        if "docker" in desc_lower:
            highlights.append("Docker is mentioned — infrastructure skills are relevant")
        if "aws" in desc_lower or "terraform" in desc_lower:
            highlights.append("Cloud/infra stack (AWS/Terraform) matches your profile")
        if "fastapi" in desc_lower:
            highlights.append("FastAPI expertise directly applicable")

        if "senior" in title_lower or "principal" in title_lower:
            concerns.append("Seniority level may be above your target range")
        if "phd" in desc_lower:
            concerns.append("PhD requirement may be a barrier")
        if "relocation" in desc_lower:
            concerns.append("Relocation requirement conflicts with remote preference")

        lines = ["[Mock LLM Analysis]"]
        if highlights:
            lines.append("Strengths: " + "; ".join(highlights) + ".")
        else:
            lines.append("No strong keyword matches found in description.")
        if concerns:
            lines.append("Concerns: " + "; ".join(concerns) + ".")

        lines.append(
            "Note: This analysis is generated by the mock provider. "
            "Connect a real LLM provider in V2 for richer insights."
        )
        return "\n".join(lines)
